### ISSUE TITLE
Slow response on mobile when picking selected emoji. 

### ISSUE THREAD

**Issue by pinchez254** [TheWidlarzGroup/rn-emoji-keyboard#51] opened 2022-02-25 14:14 UTC
**Describe the bug**
The following warning is displayed.
`VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc. {"contentLength": 4525.71435546875, "dt": 2628, "prevDt": 2827}`

**To Reproduce**
1. Go to onEmojiSelected prop
2. add a callback ` onEmojiSelected={emoji => {
          console.log(emoji);
        }}`
3. click emoji more than one time

**Comment by jakex7** [comment] 2022-09-27 20:15
Hi @pinchez254 ,
We couldn't reproduce this issue and it's related to the old version of rn-emoji-keyboard.
I'm closing this for now, but feel free to reopen if the problem persists 🙂

**Closed by jakex7** 2022-09-27 20:15 UTC
Labels: bug
