### ISSUE TITLE
Unable to scroll & select emojis in some categories.

### ISSUE THREAD

**Issue by crumb1e** [TheWidlarzGroup/rn-emoji-keyboard#138] opened 2023-06-09 16:10 UTC
**Describe the bug**
Some of the categories are un-scrollable & unable to pick the top few rows of these categories. Can expand modal to cause the category to become scrollable.

**To Reproduce**
I haven't done any tweaking besides setting a theme. So not many steps to reproduce apart from:

1. install package
2. use package

**Expected behavior**
I'd expect to be able to scroll each category correctly

**Screenshots**
![emoji-menu-bug-2](https://github.com/TheWidlarzGroup/rn-emoji-keyboard/assets/18497168/04e828a0-8f8f-46ea-9300-fbbcc5d5041b)

This happens on both iOS and Android. Using Expo 48.

**Comment by mateki0** [comment] 2023-06-13 13:39
Hi, thanks for reporting. Can you add a minimal reproducible code here - https://snack.expo.dev/? I've tried to reproduce it by myself in 2 applications and I couldn't so it may be something specific to your project

**Comment by yefim** [comment] 2023-07-06 20:04
I see this too. The first 2 default categories work and so does the last category. I can repro it in my app but not a basic template. It's definitely something in my app.

**Comment by yefim** [comment] 2023-07-06 20:59
I'm trying to narrow it down and looks like the react emoji picker bugs out whenever a react-reanimated animation plays :(

**Comment by Okelm** [comment] 2023-07-06 21:22
@yefim thanks for co-reporting, it seems that we might need to look into prioritizing reanimated integration[ in our roadmap ](https://github.com/TheWidlarzGroup/rn-emoji-keyboard/issues/144)

@crumb1e have you been able to find a solution in your case? Happy to look into it more carefully though we need more info first

**Comment by crumb1e** [comment] 2023-07-06 21:24
> @yefim thanks for co-reporting, it seems that we might need to look into prioritizing reanimated integration[ in our roadmap ](https://github.com/TheWidlarzGroup/rn-emoji-keyboard/issues/144)
> 
> 
> 
> @crumb1e have you been able to find a solution in your case? Happy to look into it more carefully though we need more info first

@Okelm Apologies been super busy, will see if I can get some more info tomorrow!

**Comment by yefim** [comment] 2023-07-06 22:13
Hmmm I'm able to get it working with some react-native-reanimated animations but not others :/ this is very peculiar. See this working as expected Snack: https://snack.expo.dev/@yefim/emoji-picker-reanimated

**Comment by yefim** [comment] 2023-07-06 22:16
When I expand the 3rd category (the broken one), I am able to scroll on the bottom half of the category. This makes it seem as if there is something on top of the top half of the ScrollView but I cannot find anything there with the inspector. Here's a video

https://github.com/TheWidlarzGroup/rn-emoji-keyboard/assets/1170843/d8edcfa0-a4b7-4103-b975-1fe0c50bf0a7

**Comment by yefim** [comment] 2023-07-06 22:27
AHA! I have a Snack that can reproduce the issue! https://snack.expo.dev/@yefim/rn-emoji-keyboard-reaniamted-expo48?sdkVersion=48.0.0

**Comment by yefim** [comment] 2023-07-06 22:28
The working Snack is using Expo 47, react-native-reanimated 2.12.0.

The broken one is using Expo 48, react-native-reanimated 2.14.4.

**Comment by yefim** [comment] 2023-07-07 14:30
Any ideas on a workaround? I can try downgrading our reanimated package

**Comment by Okelm** [comment] 2023-07-07 17:06
Havent got a chance to reproduce and compare, any kind of investigation like this would be appreciated. Go ahead @yefim !

**Comment by yefim** [comment] 2023-07-07 18:58
Did you check out the Snack I linked with the reproduction? https://github.com/TheWidlarzGroup/rn-emoji-keyboard/issues/138#issuecomment-1624387514

I'm not able to downgrade the react-native-reanimated library in my project :(

**Comment by mateki0** [comment] 2023-07-08 09:24
Hi, thanks for the repro @yefim I've been looking at it, but I haven't figure out how to fix it yet. For now I know that the problem are layout entering animations. So if u want an instant fix, you have to get rid of them for now, and I will try to find a fix as fast as possible :)

**Comment by mateki0** [comment] 2023-07-10 09:05
@yefim @crumb1e I have found a solution. You had problems only on iOS right? Because I couldn't reproduce it on Android.
https://github.com/TheWidlarzGroup/rn-emoji-keyboard/pull/145

**Comment by yefim** [comment] 2023-07-10 15:33
Yes, I'm only seeing this on iOS. We aren't currently building on Android.

**Comment by jakex7** [comment] 2023-07-20 18:40
Hi @crumb1e @yefim 
Thanks for reporting this issue, it has been resolved by @mateki0 and released in the latest [version 1.5.0](https://github.com/TheWidlarzGroup/rn-emoji-keyboard/releases/tag/v1.5.0). I highly encourage you to update and test if everything works properly. If there is something that still needs improvement, please let us know 😄

**Closed by jakex7** 2023-07-20 18:40 UTC
Labels: bug

**Comment by yefim** [comment] 2023-07-20 20:38
it works thank you !

**Comment by OwenMelbz** [comment] 2023-07-21 08:24
On behalf of crumb1e, we've just updated to 1.5.0 so will keep an eye out :) thanks!
